### ISSUE TITLE
Missing information about twins

### ISSUE THREAD

**Issue by fplazaonate** [yue-clare-lou/Well2WellContaminationPublication#2]
Hi,

In the paper, it is mentioned that two infants are twins (#122 and #123).
I was wondering if there were any others?

Thanks,
Florian

**Comment by yue-clare-lou** [comment]
Hey Florian,

Here are the siblings:

- #7,#133 (siblings) - we did a deep dive into this pair in our 2021 publication ([Lou et al.2021](https://www.sciencedirect.com/science/article/pii/S2666379121002512?via%3Dihub))
- #58,#59,#60 (triplets)
- #122,#123 (twins)

**Comment by fplazaonate** [comment]
Thank you so much! It explains many things.
